pipeline {
    agent {
        node {
            label 'docker-host-noafs'
        }
    }

    parameters{
        string(name: 'BRANCH', defaultValue: 'master', description: 'The branch of root to build')
    }

    stages {
        stage('Build all images') {
            matrix {
                agent {
                    node {
                        label 'docker-host-noafs'
                    }
                }
                axes {
                    axis {
                        name 'IMAGE'
                        values 'ghcr.io/olemorud/ubuntu:buildready', 'ghcr.io/olemorud/centos7:buildready'
                    }
                }
                stages {
                    stage('Build') {
                        agent {
                            docker {
                                image "${IMAGE}"
                                args '''
                                    --net=host
                                    --pull=always
                                    -u=root
                                    -e BRANCH=${params.BRANCH}
                                    --volume /cvmfs:/cvmfs:shared    
                                '''
                                reuseNode true
                            }
                        }
                        steps {
                            sh '''
                                # DEBUGGING
                                ls /cvmfs
                                env
                            
                                # BUILD
                                cd /tmp/

                                for retry in {1..5}; do
                                    git clone -b $BRANCH --single-branch --depth 1 https://github.com/root-project/root.git \
                                    && ERR=false && break
                                done

                                mkdir -p /tmp/build
                                cd /tmp/build

                                # For ROOT version 6.26.00 set `-Druntime_cxxmodules=OFF` (https://github.com/root-project/root/pull/10198)
                                cmake /tmp/root/ \
                                    -DCMAKE_CXX_STANDARD=17 \
                                    -Dgnuinstall=ON \
                                    -Dsoversion=ON \
                                    -DCMAKE_INSTALL_PREFIX=/usr \
                                    -DCMAKE_INSTALL_BINDIR=bin \
                                    -DCMAKE_INSTALL_CMAKEDIR=lib/x86_64-linux-gnu/cmake/ROOT \
                                    -DCMAKE_INSTALL_DATAROOTDIR=share \
                                    -DCMAKE_INSTALL_DATADIR=share/root \
                                    -DCMAKE_INSTALL_DOCDIR=share/doc/root \
                                    -DCMAKE_INSTALL_ELISPDIR=share/emacs/site-lisp \
                                    -DCMAKE_INSTALL_FONTDIR=share/root/fonts \
                                    -DCMAKE_INSTALL_ICONDIR=share/root/icons \
                                    -DCMAKE_INSTALL_INCLUDEDIR=include/ROOT \
                                    -DCMAKE_INSTALL_JSROOTDIR=share/root/js \
                                    -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu \
                                    -DCMAKE_INSTALL_MACRODIR=share/root/macros \
                                    -DCMAKE_INSTALL_MANDIR=share/man \
                                    -DCMAKE_INSTALL_OPENUI5DIR=share/root/ui5 \
                                    -DCMAKE_INSTALL_PYTHONDIR=lib/python3/dist-packages \
                                    -DCMAKE_INSTALL_SRCDIR=/dev/null \
                                    -DCMAKE_INSTALL_SYSCONFDIR=/etc/root \
                                    -DCMAKE_INSTALL_TUTDIR=share/root/tutorials

                                cmake --build . --target install -- -j$(nproc) install
                                rm -rf /tmp/build /tmp/root'''
                        }
                    }
                }
            }
        }
    }

}
