pipeline {
    agent {
        node {
            label 'docker-host-noafs'
        }
    }

    parameters{
        string(name: 'BRANCH', defaultValue: 'master', description: 'The branch of root to build')
        //string(name: 'BUILD_OPTIONS', defaultValue: '', description: 'Options to pass to CMake, e.g. -DCMAKE_CXX_STANDARD=17')
        string(name: 'IMAGE', defaultValue: 'ubuntu22', description: 'The image to build, available images are here: https://github.com/olemorud/root-build-ready')
    }

    stages {
        stage('Set display name'){
            steps {
                script {
                    currentBuild.displayName = "${IMAGE}-${BRANCH}"
                }
            }
        }
        stage('Build') {
            agent {
                docker {
                    image "ghcr.io/olemorud/${params.IMAGE}:buildready"
                    args '''
                        --net=host
                        --pull=always
                        -u=root
                        -e BRANCH=${params.BRANCH}
                    '''
                    reuseNode true
                }
            }
            steps {
                sh 'bash ./jenkins/build.sh'
            }
            post {
                failure {
                    mattermostSend (
                        channel: '#jenkins-notification-test',
                        endpoint: 'https://mattermost.web.cern.ch/hooks/x9pg89zxw78oikemnw5huafn7e',
                        color: 'good',
                        message: "Build failed - Branch \"${BRANCH}\" on platform \"${IMAGE}\"",
                        icon: 'https://toppng.com/uploads/preview/butthead-acdc-11549475832jltej3r74n.png'
                    )
                }
            }
        }
    }
}
