pipeline {
    agent {
        node {
            label 'docker-host-noafs'
        }
    }

    parameters{
        string(name: 'BRANCH', defaultValue: 'master', description: 'The branch of root to build')
    }

    stages {
        stage('Build all images') {
            matrix {
                agent {
                    node {
                        label 'docker-host-noafs'
                    }
                }
                axes {
                    axis {
                        name 'IMAGE'
                        values 'ghcr.io/olemorud/ubuntu:buildready', 'ghcr.io/olemorud/centos7:buildready'
                    }
                }
                stages {
                    stage('Build') {
                        agent {
                            docker {
                                image "${IMAGE}"
                                args '''
                                    --net=host
                                    --pull=always
                                    -u=root
                                    -e BRANCH=${params.BRANCH}
                                    -e IMAGE=${IMAGE}
                                    --volume /cvmfs:/cvmfs:shared    
                                '''
                                reuseNode true
                            }
                        }
                        steps {
                            
                            sh '''
                                # DEBUGGING
                                ls /cvmfs
                                env
                                date
                            
                                # BUILD
                                cd /tmp/

                                # might be a security risk but no code from the git is executed
                                export GIT_SSL_NO_VERIFY=1 

                                for retry in {1..5}; do
                                    git clone -b $BRANCH --single-branch --depth 1 https://github.com/root-project/root.git \
                                    && ERR=false && break
                                done

                                mkdir -p /tmp/build
                                cd /tmp/build

                                # For ROOT version 6.26.00 set `-Druntime_cxxmodules=OFF` (https://github.com/root-project/root/pull/10198)
                                cmake /tmp/root/ -DCMAKE_INSTALL_PREFIX=/usr $OPTIONS

                                cmake --build . --target install -- -j$(nproc)
                                rm -rf /tmp/build /tmp/root
                            '''
                        }
                    }
                }
                post {
                    failure {
                        echo "# testing locally"
                        echo "docker run --rm -it --volume /cvmfs/cvmfs:shared ghcr.io/olemorud/${IMAGE}"
                        echo "# in image:"
                        echo "cd tmp"
                        echo "git clone -b ${params.BRANCH} --single-branch --depth 1 https://github.com/root-project/root.git"
                        echo "mkdir build install"
                        echo "cmake ./root -DCMAKE_INSTALL_PREFIX=./install $OPTIONS"
                        echo "cmake --build . --target install -- -j\$(nproc)"
                    }
                }
            }
        }
    }

}
