
name: 'Build ROOT multi-platform'

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        image: ["fedora32", "fedora34", "centos8", "ubuntu18", "ubuntu20", "ubuntu22"]
      fail-fast: false

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/olemorud/${{ matrix.image }}:buildready
      options: '--pull=always -u=root -e BRANCH=master'
      env:
        OS_APPLICATION_CREDENTIAL_ID: 'fdbb885970e547a49e3dfc339ce1efa7'
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: 'v3applicationcredential'
        OS_AUTH_URL: 'https://keystone.cern.ch/v3'
        OS_IDENTITY_API_VERSION: 3
        OS_INTERFACE: 'public'
        OS_REGION_NAME: 'cern'
        PLATFORM: ${{ matrix.image }}
        CONFIG: 'Release'
        INCREMENTAL: 'true'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install root
        run: 'python3 -u .github/workflows/installroot.py'

