
name: 'Build ROOT multi-platform'

on: 
  workflow_dispatch:
    inputs:
      incremental:
        description: 'Do incremental build'
        required: false
        default: 'true'
      force_generation:
        description: 'Incremental build: Make sure generation step is always run'
        required: false
        default: 'false'
  schedule:
    - cron: '0 1 * * *'


jobs:
  build:
    strategy:
      matrix:
        image: ["fedora32", "fedora34", "centos8", "ubuntu18", "ubuntu20", "ubuntu22"]
      fail-fast: false

    runs-on: [self-hosted, linux, x64]

    container:
      image: ghcr.io/olemorud/${{ matrix.image }}:buildready
      options: '--pull=always -u=123 -e BRANCH=master --net=host'
      env:
        OS_APPLICATION_CREDENTIAL_ID: 'fdbb885970e547a49e3dfc339ce1efa7'
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: 'v3applicationcredential'
        OS_AUTH_URL: 'https://keystone.cern.ch/v3'
        OS_IDENTITY_API_VERSION: 3
        OS_INTERFACE: 'public'
        OS_REGION_NAME: 'cern'
        PLATFORM: ${{ matrix.image }}
        CONFIG: 'Release'
        INCREMENTAL: ${{ inputs.incremental }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Nightly build
        if:   github.event.schedule == '0 1 * * *'
        run: 'INCREMENTAL=true python3 -u .github/workflows/rootci-installers/build_root.py'

      - name: Install root
        run:  python3 -u .github/workflows/rootci-installers/build_root.py --alwaysgenerate=${{ inputs.force_generation }}

