
name: 'ROOT CI'

on:
  # Enables manual start of workflow
  workflow_dispatch:
    inputs:
      head_ref:
        description: rebase from ...
        type: string
        required: true
        default: master
      base_ref:
        description: ... to ... (can have same value)
        type: string
        required: true
        default: master
      incremental:
        description: 'Do incremental build'
        type: boolean
        required: true
        default: true

jobs:
  create_annotations_in_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        level: ["warning", "error"]
        message: ["foo", "bar"]
    steps:
      - name: Create annotation
        run: echo "::${{ matrix.level }}::${{ matrix.message }}"
  

  event_file:
    if: github.repository_owner == 'root-project' || github.event_name == 'pull_request'
    name: "Upload Event Payload"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Event File
        path: ${{ github.event_path }}
