
name: Test Summary PR comment

on:
  workflow_run:
    # do NOT use quotes: https://stackoverflow.com/a/72551795/17876693
    workflows: [ROOT CI]
    types:
      - completed
permissions: {}

jobs:
  comment-test-results:
    name: Publish Test Results

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
      - name: Print the ID of the run that triggered this
        env:
          ID: ${{ github.event.workflow_run.id }}
        run: echo "$ID"