
name: Test Summary PR comment

on:
  workflow_run:
    # do NOT use quotes: https://stackoverflow.com/a/72551795/17876693
    workflows: [ROOT CI]
    types:
      - completed

jobs:
  comment-test-results:
    name: Publish Test Results

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Print the annotations of the run that triggered this
        env:
          workflow_id: ${{ github.event.workflow_run.id }}
          GH_TOKEN: ${{ github.token }}
        run: |
          cd .github/workflows/
          npm install octokit
          ./annotations.mjs

#      - name: Print the annotations of the run that triggered this
#        env:
#          workflow_id: ${{ github.event.workflow_run.id }}
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          set -x
#
#          run_ids=$(gh api -H "Accept: application/vnd.github+json" \
#              -H "X-GitHub-Api-Version: 2022-11-28" \
#              /repos/${{ github.repository }}/actions/runs/${workflow_id}/jobs | jq '.jobs[].id'
#          )
#
#          echo "run ids: $run_ids"
#
#          for id in $run_ids; do
#              gh api \
#                -H "Accept: application/vnd.github+json"  \
#                -H "X-GitHub-Api-Version: 2022-11-28"     \
#                /repos/${{ github.repository }}/check-runs/$id/annotations \
#              | jq '.[] | select(.annotation_level == "warning" or .annotation_level == "error")'
#          done