
name: Test Summary PR comment

on:
  workflow_run:
    # do NOT use quotes: https://stackoverflow.com/a/72551795/17876693
    workflows: [ROOT CI]
    types:
      - completed
permissions: {}

jobs:
  comment-test-results:
    name: Publish Test Results

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
      - name: Dump github.event.workflow_run
        env:
          RUN: ${{ toJSON( github.event.workflow_run ) }}
        run: echo "$RUN"

      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           mkdir -p artifacts && cd artifacts

           artifacts_url=${{ github.event.workflow_run.artifacts_url }}

           gh api --paginate "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
           do
             IFS=$'\t' read name url <<< "$artifact"
             gh api $url > "$name.zip"
             unzip -d "$name" "$name.zip"
           done