
name: 'Test'

on: 
  workflow_dispatch:

jobs:
  no-container:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Print debug info
        run:  'printf "%s@%s\\n" $(whoami) $(hostname); pwd; ls -la; ls -la /'

      - name: Attempt illegal write operation
        run:  'if touch /a; then false; else true; fi'

      - name: Attempt illegal read operation
        run:  'if cd /root; then false; else true; fi'

  in-container:
    strategy:
      fail-fast: false
      matrix:
        image: ["","","","","","","","","","","","","","","","","","","","",]

    runs-on: [self-hosted, linux, x64]

    container:
      image: ubuntu
      options: '--pull=always -v /:/mnt/test'

    steps:
      - name: Print debug info
        run:  'printf "%s@%s\\n" $(whoami) $(hostname); pwd; ls -la; ls -la /'

      - name: Attempt illegal write operation
        run:  'if touch /a; then false; else true; fi'

      - name: Attempt illegal read operation
        run:  'if cd /root; then false; else true; fi'
